In [90]:
import numpy as np

In [94]:
now=np.zeros((8,8))

In [95]:
now[2:5,3]=1
now[3,2:5]=1

In [141]:
update_mat=np.zeros((8,8))
p=now.shape[1]-1
for i in range(1,p):
    for j in range(1,p):
        n_surv=now[max(0,(i-1)):(min(p,(i+1))+1),max(0,(j-1)):(min(p,(j+1))+1)].sum()
        if now[i,j]==0:
            update=1 if n_surv==3 else 0
        else :
            update=1 if n_surv==4 or n_surv==3 else 0
        update_mat[i,j]=update

print(update_mat)
print((update_mat-now)+((update_mat+now)>=2)*2)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  2.  1.  0.  0.  0.]
 [ 0.  0.  2. -1.  2.  0.  0.  0.]
 [ 0.  0.  1.  2.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [142]:
def surv_game(now):
    p=now.shape[1]-1
    for i in range(1,p):
        for j in range(1,p):
            n_surv=now[max(0,(i-1)):(min(p,(i+1))+1),max(0,(j-1)):(min(p,(j+1))+1)].sum()
            if now[i,j]==0:
                update=1 if n_surv==3 else 0
            else :
                update=1 if n_surv==4 or n_surv==3 else 0
            update_mat[i,j]=update
    return(update_mat)
    

In [143]:
surv_game(now)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])