# Chapter04 NumPy 기본 : 배열과 벡터 연산

+ NumPy에서 제공하는 것들
    + 효율적인 다차원 배열인 ndarray는 빠른 배열 계산과 유연한 브로드캐스팅 기능을 제공한다
    + 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는표준 수학 함수
    + 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구
    + 선형대수, 난 생성기, 푸리에 변환 가능
    + C,C++,포트란으로 작성한 코드를 연결할 수 있는 C API

In [1]:
import numpy as np

In [2]:
my_arr=np.arange(1000000)

In [3]:
my_list=list(range(1000000))

In [6]:
%time for _ in range(10): my_arr2=my_arr*2

CPU times: user 11.8 ms, sys: 5.14 ms, total: 16.9 ms
Wall time: 16.9 ms


In [7]:
%time for _ in range(10): my_list=[x*2 for x in my_list]

CPU times: user 617 ms, sys: 131 ms, total: 748 ms
Wall time: 747 ms


+ NumPy를 사용한 코드가 순수 파이썬으로 작성한 코드보다 10배에서 백배이상 빠르고 메모리도 더 적게 사용함

## 4.1 NumPy ndarray:다차원 배열 객체

+ ndarray : N차원의 배열 객체

In [8]:
import numpy as np

In [9]:
data = np.random.randn(2,3)

In [10]:
data

array([[ 1.7123493 ,  0.77584524,  1.47295402],
       [ 0.75360009, -2.32642215, -1.60828407]])

In [11]:
data*10

array([[ 17.12349303,   7.7584524 ,  14.72954022],
       [  7.53600094, -23.26422148, -16.0828407 ]])

In [12]:
data*data

array([[2.93214014, 0.60193584, 2.16959355],
       [0.5679131 , 5.41224001, 2.58657765]])

In [13]:
data+data

array([[ 3.42469861,  1.55169048,  2.94590804],
       [ 1.50720019, -4.6528443 , -3.21656814]])

In [14]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

### 4.1.1 ndarray 생성하기

In [16]:
data1=[6,7.5,8,0,1]

In [17]:
arr1=np.array(data1)

In [19]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [20]:
data2=[[1,2,3,4],[5,6,7,8]]

In [21]:
arr2=np.array(data2)

In [22]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr2.ndim

2

In [24]:
arr2.shape

(2, 4)

In [25]:
arr1.dtype

dtype('float64')

In [26]:
arr2.dtype

dtype('int64')

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
np.empty((2,3,2))

array([[[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  2.14321575e-312],
        [ 1.73060410e-077, -2.32036073e+077]]])

+ np.empty 는 쓰레기값으로 채워진 배열을 반환(0으로 된 배열 아님!)

In [31]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

+ 배열생성함수
    + array
    + asarray
    + arange
    + ones, ones_like
    + zeros, zeros_like
    + empty, empty_like
    + full, full_like
    + eye, identity

In [33]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.ones_like(arr2)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [38]:
np.full([2,2],67,dtype='int')

array([[67, 67],
       [67, 67]])

In [39]:
np.full_like(arr2,67,dtype='int')

array([[67, 67, 67, 67],
       [67, 67, 67, 67]])

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 4.1.2 ndarray 의 dtype 

In [2]:
arr1 = np.array([1,2,3],dtype=np.float64)

In [3]:
arr2=np.array([1,2,3],dtype=np.int32)

In [4]:
arr1.dtype

dtype('float64')

In [5]:
arr2.dtype

dtype('int32')

In [6]:
arr = np.array([1,2,3,4,5])

In [7]:
arr.dtype

dtype('int64')

In [8]:
float_arr=arr.astype(np.float64)

In [9]:
float_arr.dtype

dtype('float64')

In [13]:
arr=np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

In [14]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [15]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [19]:
numeric_strings=np.array(['1.25','-9.6','42'],dtype=np.string_)

In [20]:
numeric_strings.dtype

dtype('S4')

In [25]:
numeric=numeric_strings.astype(float)

In [26]:
numeric

array([ 1.25, -9.6 , 42.  ])

In [27]:
numeric.dtype

dtype('float64')

In [28]:
int_array = np.arange(10)

In [29]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
calibers=np.array([.22,.270,.357,.380,.44,.50],dtype=np.float64)

In [39]:
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [40]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [66]:
empty_uint32=np.empty(8,dtype='u4')

In [67]:
empty_uint32

array([ 959525937,  758593121, 1650799924,  875639853, 1631137123,
        959263033,  925972275,  942880304], dtype=uint32)

### 4.1.3 NumPy 배열의 산술 연산

In [73]:
arr=np.array([[1.,2.,3.],[4.,5.,6.]])

In [75]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [76]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [78]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [79]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [80]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [81]:
arr2=np.array([[0,4,1],[7,2,12]],dtype=np.float64)

In [84]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [85]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

+ 크기가 다른 배열간의 연산은 **브로드캐스팅(broadcasting)** 이라고 한다.

### 4.1.4 색인과 슬라이싱 기초